// 102 Badges for Gamification System - Complete List
export const BADGES = [
  // Mood Tracking (15)
  { name: 'First Mood', description: 'Log your first mood', icon: '🎯', category: 'mood', rarity: 'common', xpReward: 10, requirement: { type: 'count', target: 1, action: 'mood_log' }, order: 1 },
  { name: 'Mood Tracker', description: 'Log 10 moods', icon: '📊', category: 'mood', rarity: 'common', xpReward: 25, requirement: { type: 'count', target: 10, action: 'mood_log' }, order: 2 },
  { name: 'Mood Master', description: 'Log 50 moods', icon: '🎖️', category: 'mood', rarity: 'rare', xpReward: 50, requirement: { type: 'count', target: 50, action: 'mood_log' }, order: 3 },
  { name: 'Mood Legend', description: 'Log 100 moods', icon: '👑', category: 'mood', rarity: 'epic', xpReward: 100, requirement: { type: 'count', target: 100, action: 'mood_log' }, order: 4 },
  { name: 'Mood Guru', description: 'Log 365 moods', icon: '🌟', category: 'mood', rarity: 'legendary', xpReward: 250, requirement: { type: 'count', target: 365, action: 'mood_log' }, order: 5 },
  { name: 'Week Warrior', description: '7 day mood streak', icon: '🔥', category: 'mood', rarity: 'common', xpReward: 30, requirement: { type: 'streak', target: 7, action: 'mood_log' }, order: 6 },
  { name: 'Month Champion', description: '30 day mood streak', icon: '💪', category: 'mood', rarity: 'rare', xpReward: 100, requirement: { type: 'streak', target: 30, action: 'mood_log' }, order: 7 },
  { name: 'Century Streak', description: '100 day mood streak', icon: '🏆', category: 'mood', rarity: 'epic', xpReward: 300, requirement: { type: 'streak', target: 100, action: 'mood_log' }, order: 8 },
  { name: 'Year of Awareness', description: '365 day mood streak', icon: '💎', category: 'mood', rarity: 'legendary', xpReward: 1000, requirement: { type: 'streak', target: 365, action: 'mood_log' }, order: 9 },
  { name: 'Happy Vibes', description: '10 positive moods', icon: '😊', category: 'mood', rarity: 'common', xpReward: 20, requirement: { type: 'count', target: 10, action: 'positive_mood' }, order: 10 },
  { name: 'Rising Star', description: 'Improve mood trend', icon: '⭐', category: 'mood', rarity: 'rare', xpReward: 50, requirement: { type: 'special', action: 'improving_trend' }, order: 11 },
  { name: 'Morning Person', description: 'Log mood before 9 AM', icon: '🌅', category: 'mood', rarity: 'common', xpReward: 25, requirement: { type: 'special', action: 'morning_logger' }, order: 12 },
  { name: 'Night Owl', description: 'Log mood after 9 PM', icon: '🦉', category: 'mood', rarity: 'common', xpReward: 25, requirement: { type: 'special', action: 'night_logger' }, order: 13 },
  { name: 'Mood Explorer', description: 'Use analytics', icon: '🔍', category: 'mood', rarity: 'rare', xpReward: 40, requirement: { type: 'special', action: 'analytics_explorer' }, order: 14 },
  { name: 'Self-Aware', description: '20 moods with notes', icon: '🧠', category: 'mood', rarity: 'common', xpReward: 30, requirement: { type: 'count', target: 20, action: 'mood_with_notes' }, order: 15 },

  // Journal (15)
  { name: 'First Words', description: 'First journal entry', icon: '✍️', category: 'journal', rarity: 'common', xpReward: 15, requirement: { type: 'count', target: 1, action: 'journal_entry' }, order: 1 },
  { name: 'Storyteller', description: '10 journal entries', icon: '📖', category: 'journal', rarity: 'common', xpReward: 30, requirement: { type: 'count', target: 10, action: 'journal_entry' }, order: 2 },
  { name: 'Author', description: '50 journal entries', icon: '📚', category: 'journal', rarity: 'rare', xpReward: 75, requirement: { type: 'count', target: 50, action: 'journal_entry' }, order: 3 },
  { name: 'Novelist', description: '100 journal entries', icon: '🖋️', category: 'journal', rarity: 'epic', xpReward: 150, requirement: { type: 'count', target: 100, action: 'journal_entry' }, order: 4 },
  { name: 'Literary Legend', description: '365 journal entries', icon: '📜', category: 'journal', rarity: 'legendary', xpReward: 500, requirement: { type: 'count', target: 365, action: 'journal_entry' }, order: 5 },
  { name: 'Wordsmith', description: '10,000 words', icon: '💬', category: 'journal', rarity: 'rare', xpReward: 60, requirement: { type: 'milestone', target: 10000, action: 'total_words' }, order: 6 },
  { name: 'Word Wizard', description: '50,000 words', icon: '🪄', category: 'journal', rarity: 'epic', xpReward: 200, requirement: { type: 'milestone', target: 50000, action: 'total_words' }, order: 7 },
  { name: 'Voice of Reason', description: '5 voice journals', icon: '🎤', category: 'journal', rarity: 'common', xpReward: 25, requirement: { type: 'count', target: 5, action: 'voice_journal' }, order: 8 },
  { name: 'Picture Perfect', description: '5 photo journals', icon: '📸', category: 'journal', rarity: 'common', xpReward: 25, requirement: { type: 'count', target: 5, action: 'photo_journal' }, order: 9 },
  { name: 'Multimedia Master', description: '10 mixed entries', icon: '🎨', category: 'journal', rarity: 'rare', xpReward: 50, requirement: { type: 'count', target: 10, action: 'mixed_journal' }, order: 10 },
  { name: 'Grateful Heart', description: '20 gratitude entries', icon: '🙏', category: 'journal', rarity: 'common', xpReward: 40, requirement: { type: 'count', target: 20, action: 'gratitude_journal' }, order: 11 },
  { name: 'Deep Thinker', description: '10 reflection entries', icon: '💭', category: 'journal', rarity: 'common', xpReward: 35, requirement: { type: 'count', target: 10, action: 'reflection_journal' }, order: 12 },
  { name: 'Dream Chaser', description: '15 goal entries', icon: '🎯', category: 'journal', rarity: 'common', xpReward: 35, requirement: { type: 'count', target: 15, action: 'goals_journal' }, order: 13 },
  { name: 'Consistent Writer', description: '7 day journal streak', icon: '✨', category: 'journal', rarity: 'common', xpReward: 40, requirement: { type: 'streak', target: 7, action: 'journal_entry' }, order: 14 },
  { name: 'Daily Chronicler', description: '30 day journal streak', icon: '📅', category: 'journal', rarity: 'rare', xpReward: 120, requirement: { type: 'streak', target: 30, action: 'journal_entry' }, order: 15 },

  // Wellness (15)
  { name: 'First Breath', description: 'First meditation', icon: '🧘', category: 'wellness', rarity: 'common', xpReward: 25, requirement: { type: 'count', target: 1, action: 'meditation_complete' }, order: 1 },
  { name: 'Zen Beginner', description: '10 meditations', icon: '🕉️', category: 'wellness', rarity: 'common', xpReward: 50, requirement: { type: 'count', target: 10, action: 'meditation_complete' }, order: 2 },
  { name: 'Mindful Soul', description: '50 meditations', icon: '☮️', category: 'wellness', rarity: 'rare', xpReward: 100, requirement: { type: 'count', target: 50, action: 'meditation_complete' }, order: 3 },
  { name: 'Meditation Master', description: '100 meditations', icon: '🌸', category: 'wellness', rarity: 'epic', xpReward: 200, requirement: { type: 'count', target: 100, action: 'meditation_complete' }, order: 4 },
  { name: 'Enlightened', description: '365 meditations', icon: '✨', category: 'wellness', rarity: 'legendary', xpReward: 500, requirement: { type: 'count', target: 365, action: 'meditation_complete' }, order: 5 },
  { name: 'Breathing Expert', description: '20 breathing exercises', icon: '💨', category: 'wellness', rarity: 'common', xpReward: 30, requirement: { type: 'count', target: 20, action: 'breathing_exercise' }, order: 6 },
  { name: 'Yoga Enthusiast', description: '15 yoga sessions', icon: '🤸', category: 'wellness', rarity: 'common', xpReward: 35, requirement: { type: 'count', target: 15, action: 'yoga_complete' }, order: 7 },
  { name: 'Sound Healer', description: '10 sound therapy', icon: '🎵', category: 'wellness', rarity: 'common', xpReward: 30, requirement: { type: 'count', target: 10, action: 'sound_therapy' }, order: 8 },
  { name: 'Wellness Warrior', description: 'Try all types', icon: '⚡', category: 'wellness', rarity: 'rare', xpReward: 75, requirement: { type: 'special', action: 'all_wellness_types' }, order: 9 },
  { name: 'Morning Ritual', description: 'Meditate before 9 AM', icon: '🌄', category: 'wellness', rarity: 'common', xpReward: 40, requirement: { type: 'special', action: 'morning_meditation' }, order: 10 },
  { name: 'Calm Streak', description: '7 day meditation streak', icon: '🔮', category: 'wellness', rarity: 'common', xpReward: 50, requirement: { type: 'streak', target: 7, action: 'meditation_complete' }, order: 11 },
  { name: 'Zen Master', description: '30 day meditation streak', icon: '🏯', category: 'wellness', rarity: 'rare', xpReward: 150, requirement: { type: 'streak', target: 30, action: 'meditation_complete' }, order: 12 },
  { name: 'Marathon Meditator', description: '60 minutes total', icon: '⏱️', category: 'wellness', rarity: 'common', xpReward: 45, requirement: { type: 'milestone', target: 60, action: 'meditation_minutes' }, order: 13 },
  { name: 'Mindfulness Marathon', description: '10 hours total', icon: '🎖️', category: 'wellness', rarity: 'epic', xpReward: 250, requirement: { type: 'milestone', target: 600, action: 'meditation_minutes' }, order: 14 },
  { name: 'Wellness Explorer', description: 'All categories', icon: '🗺️', category: 'wellness', rarity: 'rare', xpReward: 80, requirement: { type: 'special', action: 'all_categories' }, order: 15 },

  // Goals (12)
  { name: 'Goal Setter', description: 'Create first goal', icon: '🎯', category: 'goals', rarity: 'common', xpReward: 10, requirement: { type: 'count', target: 1, action: 'goal_created' }, order: 1 },
  { name: 'Ambitious', description: 'Create 10 goals', icon: '🚀', category: 'goals', rarity: 'common', xpReward: 25, requirement: { type: 'count', target: 10, action: 'goal_created' }, order: 2 },
  { name: 'First Victory', description: 'Complete first goal', icon: '🏅', category: 'goals', rarity: 'common', xpReward: 20, requirement: { type: 'count', target: 1, action: 'goal_completed' }, order: 3 },
  { name: 'Achiever', description: 'Complete 5 goals', icon: '🎊', category: 'goals', rarity: 'common', xpReward: 50, requirement: { type: 'count', target: 5, action: 'goal_completed' }, order: 4 },
  { name: 'Goal Crusher', description: 'Complete 25 goals', icon: '💪', category: 'goals', rarity: 'rare', xpReward: 100, requirement: { type: 'count', target: 25, action: 'goal_completed' }, order: 5 },
  { name: 'Unstoppable', description: 'Complete 100 goals', icon: '⚡', category: 'goals', rarity: 'epic', xpReward: 300, requirement: { type: 'count', target: 100, action: 'goal_completed' }, order: 6 },
  { name: 'Habit Builder', description: '7 day goal streak', icon: '🔥', category: 'goals', rarity: 'common', xpReward: 35, requirement: { type: 'streak', target: 7, action: 'goal_streak' }, order: 7 },
  { name: 'Consistency King', description: '30 day goal streak', icon: '👑', category: 'goals', rarity: 'rare', xpReward: 100, requirement: { type: 'streak', target: 30, action: 'goal_streak' }, order: 8 },
  { name: 'Century Streak', description: '100 day goal streak', icon: '💯', category: 'goals', rarity: 'epic', xpReward: 250, requirement: { type: 'streak', target: 100, action: 'goal_streak' }, order: 9 },
  { name: 'Milestone Master', description: 'Complete milestone goal', icon: '🏔️', category: 'goals', rarity: 'rare', xpReward: 60, requirement: { type: 'special', action: 'milestone_complete' }, order: 10 },
  { name: 'Perfect Week', description: 'Complete all daily goals', icon: '⭐', category: 'goals', rarity: 'rare', xpReward: 75, requirement: { type: 'special', action: 'perfect_week' }, order: 11 },
  { name: 'Goal Variety', description: 'All goal categories', icon: '🌈', category: 'goals', rarity: 'common', xpReward: 40, requirement: { type: 'special', action: 'all_goal_categories' }, order: 12 },

  // Social (10)
  { name: 'First Connection', description: 'First buddy match', icon: '🤝', category: 'social', rarity: 'common', xpReward: 15, requirement: { type: 'count', target: 1, action: 'buddy_matched' }, order: 1 },
  { name: 'Social Butterfly', description: '5 buddy matches', icon: '🦋', category: 'social', rarity: 'common', xpReward: 30, requirement: { type: 'count', target: 5, action: 'buddy_matched' }, order: 2 },
  { name: 'Community Builder', description: '10 buddy matches', icon: '🏘️', category: 'social', rarity: 'rare', xpReward: 60, requirement: { type: 'count', target: 10, action: 'buddy_matched' }, order: 3 },
  { name: 'Conversation Starter', description: '50 messages sent', icon: '💬', category: 'social', rarity: 'common', xpReward: 25, requirement: { type: 'count', target: 50, action: 'messages_sent' }, order: 4 },
  { name: 'Supportive Friend', description: '10 check-ins', icon: '💝', category: 'social', rarity: 'common', xpReward: 40, requirement: { type: 'count', target: 10, action: 'check_ins' }, order: 5 },
  { name: 'Team Player', description: '5 shared activities', icon: '🎯', category: 'social', rarity: 'common', xpReward: 35, requirement: { type: 'count', target: 5, action: 'shared_activities' }, order: 6 },
  { name: 'Goal Partner', description: '3 shared goals', icon: '🤜🤛', category: 'social', rarity: 'common', xpReward: 30, requirement: { type: 'count', target: 3, action: 'shared_goals' }, order: 7 },
  { name: 'Reliable Buddy', description: '30 day buddy relationship', icon: '🌟', category: 'social', rarity: 'rare', xpReward: 75, requirement: { type: 'milestone', target: 30, action: 'buddy_days' }, order: 8 },
  { name: 'Community Star', description: '10 positive ratings', icon: '⭐', category: 'social', rarity: 'rare', xpReward: 50, requirement: { type: 'count', target: 10, action: 'positive_ratings' }, order: 9 },
  { name: 'Icebreaker Pro', description: '20 icebreakers used', icon: '🎭', category: 'social', rarity: 'common', xpReward: 20, requirement: { type: 'count', target: 20, action: 'icebreakers_used' }, order: 10 },

  // Streak (10)
  { name: 'Getting Started', description: '3 day app streak', icon: '🌱', category: 'streak', rarity: 'common', xpReward: 15, requirement: { type: 'streak', target: 3, action: 'app_usage' }, order: 1 },
  { name: 'Week Warrior', description: '7 day app streak', icon: '🔥', category: 'streak', rarity: 'common', xpReward: 30, requirement: { type: 'streak', target: 7, action: 'app_usage' }, order: 2 },
  { name: 'Two Week Champion', description: '14 day app streak', icon: '💪', category: 'streak', rarity: 'common', xpReward: 50, requirement: { type: 'streak', target: 14, action: 'app_usage' }, order: 3 },
  { name: 'Month Master', description: '30 day app streak', icon: '🏆', category: 'streak', rarity: 'rare', xpReward: 100, requirement: { type: 'streak', target: 30, action: 'app_usage' }, order: 4 },
  { name: 'Quarter Champion', description: '90 day app streak', icon: '🎖️', category: 'streak', rarity: 'epic', xpReward: 250, requirement: { type: 'streak', target: 90, action: 'app_usage' }, order: 5 },
  { name: 'Half Year Hero', description: '180 day app streak', icon: '🌟', category: 'streak', rarity: 'epic', xpReward: 500, requirement: { type: 'streak', target: 180, action: 'app_usage' }, order: 6 },
  { name: 'Year of Dedication', description: '365 day app streak', icon: '💎', category: 'streak', rarity: 'legendary', xpReward: 1000, requirement: { type: 'streak', target: 365, action: 'app_usage' }, order: 7 },
  { name: 'Comeback Kid', description: 'Restart after breaking', icon: '🔄', category: 'streak', rarity: 'common', xpReward: 20, requirement: { type: 'special', action: 'streak_restart' }, order: 8 },
  { name: 'Streak Saver', description: 'Last hour save', icon: '⏰', category: 'streak', rarity: 'rare', xpReward: 40, requirement: { type: 'special', action: 'last_minute_save' }, order: 9 },
  { name: 'Unbreakable', description: '100 days no miss', icon: '🛡️', category: 'streak', rarity: 'epic', xpReward: 300, requirement: { type: 'streak', target: 100, action: 'app_usage' }, order: 10 },

  // Milestone (13)
  { name: 'Welcome Aboard', description: 'Complete profile', icon: '👋', category: 'milestone', rarity: 'common', xpReward: 10, requirement: { type: 'special', action: 'profile_complete' }, order: 1 },
  { name: 'First Week', description: '7 days active', icon: '📅', category: 'milestone', rarity: 'common', xpReward: 25, requirement: { type: 'milestone', target: 7, action: 'days_active' }, order: 2 },
  { name: 'One Month', description: '30 days active', icon: '🗓️', category: 'milestone', rarity: 'rare', xpReward: 75, requirement: { type: 'milestone', target: 30, action: 'days_active' }, order: 3 },
  { name: 'Three Months', description: '90 days active', icon: '📆', category: 'milestone', rarity: 'epic', xpReward: 200, requirement: { type: 'milestone', target: 90, action: 'days_active' }, order: 4 },
  { name: 'Half Year', description: '180 days active', icon: '🎊', category: 'milestone', rarity: 'epic', xpReward: 400, requirement: { type: 'milestone', target: 180, action: 'days_active' }, order: 5 },
  { name: 'One Year Anniversary', description: '365 days active', icon: '🎂', category: 'milestone', rarity: 'legendary', xpReward: 1000, requirement: { type: 'milestone', target: 365, action: 'days_active' }, order: 6 },
  { name: 'Early Bird', description: 'Login before 7 AM', icon: '🌅', category: 'milestone', rarity: 'common', xpReward: 15, requirement: { type: 'special', action: 'early_login' }, order: 7 },
  { name: 'Night Shift', description: 'Login after midnight', icon: '🌙', category: 'milestone', rarity: 'common', xpReward: 15, requirement: { type: 'special', action: 'late_login' }, order: 8 },
  { name: 'Weekend Warrior', description: 'Weekend usage', icon: '🎉', category: 'milestone', rarity: 'common', xpReward: 20, requirement: { type: 'special', action: 'weekend_usage' }, order: 9 },
  { name: 'Feature Explorer', description: 'Try all features', icon: '🧭', category: 'milestone', rarity: 'rare', xpReward: 60, requirement: { type: 'special', action: 'all_features' }, order: 10 },
  { name: 'Power User', description: '100 total actions', icon: '⚡', category: 'milestone', rarity: 'rare', xpReward: 80, requirement: { type: 'milestone', target: 100, action: 'total_actions' }, order: 11 },
  { name: 'Super User', description: '500 total actions', icon: '🦸', category: 'milestone', rarity: 'epic', xpReward: 250, requirement: { type: 'milestone', target: 500, action: 'total_actions' }, order: 12 },
  { name: 'MindMate Legend', description: '1000 total actions', icon: '👑', category: 'milestone', rarity: 'legendary', xpReward: 750, requirement: { type: 'milestone', target: 1000, action: 'total_actions' }, order: 13 },

  // Special (12)
  { name: 'Safety First', description: 'Create safety plan', icon: '🛡️', category: 'special', rarity: 'rare', xpReward: 50, requirement: { type: 'special', action: 'safety_plan_created' }, order: 1 },
  { name: 'Crisis Prepared', description: 'Update safety plan 3x', icon: '🆘', category: 'special', rarity: 'rare', xpReward: 40, requirement: { type: 'count', target: 3, action: 'safety_plan_updated' }, order: 2 },
  { name: 'Helping Hand', description: 'Share a resource', icon: '🤲', category: 'special', rarity: 'common', xpReward: 25, requirement: { type: 'special', action: 'resource_shared' }, order: 3 },
  { name: 'Feedback Hero', description: 'Submit feedback', icon: '💡', category: 'special', rarity: 'common', xpReward: 30, requirement: { type: 'special', action: 'feedback_submitted' }, order: 4 },
  { name: 'Beta Tester', description: 'Try new feature', icon: '🧪', category: 'special', rarity: 'rare', xpReward: 50, requirement: { type: 'special', action: 'beta_feature' }, order: 5 },
  { name: 'Perfect Day', description: 'Complete all daily tasks', icon: '🌟', category: 'special', rarity: 'rare', xpReward: 60, requirement: { type: 'special', action: 'perfect_day' }, order: 6 },
  { name: 'Mood Variety', description: 'Log all mood levels', icon: '🎨', category: 'special', rarity: 'common', xpReward: 35, requirement: { type: 'special', action: 'all_moods' }, order: 7 },
  { name: 'Time Traveler', description: 'Use at all hours', icon: '⏰', category: 'special', rarity: 'rare', xpReward: 45, requirement: { type: 'special', action: 'all_hours' }, order: 8 },
  { name: 'Seasonal User', description: 'Use in all seasons', icon: '🍂', category: 'special', rarity: 'epic', xpReward: 100, requirement: { type: 'special', action: 'all_seasons' }, order: 9 },
  { name: 'Birthday Bonus', description: 'Login on birthday', icon: '🎂', category: 'special', rarity: 'rare', xpReward: 50, requirement: { type: 'special', action: 'birthday_login' }, order: 10 },
  { name: 'New Year, New You', description: 'Login on Jan 1st', icon: '🎆', category: 'special', rarity: 'common', xpReward: 30, requirement: { type: 'special', action: 'newyear_login' }, order: 11 },
  { name: 'Holiday Spirit', description: 'Login on holiday', icon: '🎄', category: 'special', rarity: 'common', xpReward: 25, requirement: { type: 'special', action: 'holiday_login' }, order: 12 }
];
